var input1 = document.getElementById('value1')
var input2 = document.getElementById('value2')
var btnSum = document.getElementById('btnSum')
var btnSub = document.getElementById('btnSub')
var btnMulti = document.getElementById('btnMulti')
var btnDiv = document.getElementById('btnDiv')
var btnPoten = document.getElementById('btnPoten')
var btnRaiz = document.getElementById('btnRaiz')
var btnFatorial = document.getElementById('btnFatorial')
var btnClear = document.getElementById('btnClear')
var output = document.getElementById('output')
var outputPrimo = document.getElementById('outputPrimo')

btnSum.addEventListener('click', sumOperation)
btnSub.addEventListener('click', subOperation)
btnMulti.addEventListener('click', multiOperation)
btnDiv.addEventListener('click', divOperation)
btnPoten.addEventListener('click', potenOperation)
btnRaiz.addEventListener('click', raiz)
btnFatorial.addEventListener('click', fatorial)
btnClear.addEventListener('click', limparCampos)