var input1 = document.getElementById('value1')
var input2 = document.getElementById('value2')
var btnSum = document.getElementById('sum')
var btnSub = document.getElementById('sub')
var btnMulti = document.getElementById('multi')
var btnDiv = document.getElementById('div')
var btnPoten = document.getElementById('poten')
var btnClear = document.getElementById('clear')
var output = document.getElementById('output')

btnSum.addEventListener('click', sumOperation)
btnSub.addEventListener('click', subOperation)
btnMulti.addEventListener('click', multiOperation)
btnDiv.addEventListener('click', divOperation)
btnPoten.addEventListener('click', potenOperation)
btnClear.addEventListener('click', limparCampos)